global:
  ingressSubdomain: mooc-one-ocp-clus-532507-0143c5dd31acd8e030a1d6e0ab1380e3-0000.us-east.containers.appdomain.cloud
  tlsSecretName: mooc-one-ocp-clus-532507-0143c5dd31acd8e030a1d6e0ab1380e3-0000

inventory-management-svc-msm:
  replicaCount: 3
  
  ingress:
    enabled: true
    tlsSecretName: mooc-one-ocp-clus-532507-0143c5dd31acd8e030a1d6e0ab1380e3-0000

